### ISSUE TITLE
VERSION file not included in released packages

### ISSUE THREAD

**Issue by zymergen-luke** [planetlabs/flake8-continuation#1]
I'm not sure what method you're using to build the package, but the packages uploaded to pypi do not include the VERSION file (you can download the uploaded package here: https://pypi.org/project/flake8-continuation/#files).

This causes `pip install flake8-continuation` to fail. I have cloned the repo, but found that a simple `python setup.py sdist` is correctly adding the VERSION file, so I'm not sure it's getting stripped from your builds.

Can you try building the package again and double check that the package includes the necessary version file?

**Comment by declension** [comment]
This also happens with `poetry install flake8-continuation` (unsurprisingly, as it uses Pip)

**Comment by ericrdunham** [comment]
I apologize for the incredibly long delay in seeing this issue @zymergen-luke and @declension. I didn't have a watch set up for this repository (since it got moved from a personal project to an organizational repository). I just now released 1.0.4 which I expect will appears to fix the version issue as well as adds support for ignoring backslashes inside docstrings.
